name: AUR Tester

on:
  schedule:
    - cron: "32 5 */3 * *"
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test-install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install AUR package
      run: ./scripts/check-aur.sh
